"""Regenerate the command reference from argparse contracts (no runtime writes)."""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from agent_board import cli, web, watch


def render() -> str:
    sections = ["# CLI reference\n\nGenerated by `python -B docs/generate_cli_reference.py`.\n"
                "Use `--repo <repo>` before the command to select project vocabulary.\n"
                "The examples below use the neutral initialized vocabulary.\n"
                "JSON is the default for inbox/list results; inbox has no `--json` flag.\n"]

    def visit(parser: argparse.ArgumentParser, command: str) -> None:
        parser.prog = command
        sections.append("\n## " + command + "\n\n```text\n" + parser.format_help().rstrip() + "\n```\n")
        for action in parser._actions:
            if isinstance(action, argparse._SubParsersAction):
                for name, child in action.choices.items():
                    visit(child, command + " " + name)

    config = {"identities": {"master"}, "message_senders": {"master", "lead", "operator"},
              "message_recipients": {"master", "lead", "operator"},
              "roadmap_owners": {"master", "shared", "unassigned"}, "workstreams": ()}
    visit(cli.build_parser(config), "agent_board.py")
    visit(web.build_parser(), "agent_board_web.py")
    visit(watch.build_parser(), "agent_board_watch.py")
    return "".join(sections)


if __name__ == "__main__":
    (ROOT / "docs" / "cli-reference.md").write_text(render(), encoding="utf-8")
